[package]
name = "ipc-benchmarks"
version = "0.1.0"
authors = ["Joel Dice <joel.dice@gmail.com>"]
edition = "2018"

[dependencies]
ipmpsc = { path = "..", features = ["fork"] }
ipc-channel = "0.14"
bincode = "1"
serde = "1"
serde_derive = "1"
serde_bytes = "0.11"
anyhow = "1"
